controller_configuration_credentials_secure_logging: true
controller_credentials:
  - name: vCenter Inventory User
    credential_type: "VMware vCenter"
    organization: Default
    description: VMware vCenter Inventory user
    inputs:
      host: "{{ vmware_vcenter_url }}"
      username: "{{ vmware_username }}"
      password: "{{ vmware_password }}"
    
