---
- name: Playbook to configure AAP controller post-installation
  hosts: all
  vars_files:
    - "../vault.yml"
  connection: local
  tasks:
    - name: Create execution environment
      ansible.builtin.include_role:
        name: infra.controller_configuration.execution_environments
       
    - name: Create Credentials
      ansible.builtin.include_role:
        name: infra.controller_configuration.credentials

    - name: Create inventories
      ansible.builtin.include_role:
        name: infra.controller_configuration.inventories
    
    - name: Create inventory sources
      ansible.builtin.include_role:
        name: infra.controller_configuration.inventory_sources
